apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-app
  namespace: demo
  labels:
    app: flask-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: flask-app
  template:
    metadata:
      labels:
        app: flask-app
    spec:
      containers:
      - name: flask-app
        image: kartikj69/test:arm64
        imagePullPolicy: Never
        ports:
        - containerPort: 5090
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /
            port: 5090
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 5090
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: flask-app-service
  namespace: demo
  labels:
    app: flask-app
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 5090
    nodePort: 30080
    protocol: TCP
  selector:
    app: flask-app 